name: Deploy to GitHub Pages (Vite + Bun)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.20  # <--- Tu versión exacta

      # 3. Instalar dependencias con Bun
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # 4. TypeScript check (opcional)
      - name: Type check
        run: bun x tsc -b

      # 5. Construir la app
      - name: Build project
        run: bun run build

      # 6. SPA fallback para React Router
      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      # 7. Evitar conflictos con Jekyll en GitHub Pages
      - name: Disable Jekyll
        run: touch dist/.nojekyll

      # 8. Subir artefacto para GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
